# Jekyll configuration for Sol Ligam website
title: "Sol Ligam"
description: "Accompagnement pour la réduction de l'impact carbone"
url: "https://solligam.fr"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Include in processing
include:
  - .well-known

# Exclude from processing
exclude:
  - archive/
  - node_modules/
  - .bundle/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
  - .git/
  - .gitignore

# Site settings
lang: fr
author: "Sol Ligam"
email: "contact@solligam.fr"

# Social/Contact
social:
  email: "contact@solligam.fr"
  instagram: "https://www.instagram.com/sol_ligam/"
  linkedin: "https://www.linkedin.com/company/sol-ligam/"
  
# Company info
company:
  name: "Sol Ligam"
  officialName: "S.A.S. Sol Ligam"
  address: "215 cours du Maréchal Gallieni, 33000 Bordeaux"
  phone: ""
  carbon_simulator: "https://monbilancarbone.solligam.fr"

# Navigation
navigation:
  - name: "Accueil"
    url: "/"
  - name: "Outils"
    url: "/outils/"
  - name: "Projets"
    url: "/projets/"
  - name: "À propos"
    url: "/a-propos/"
  - name: "Contact"
    url: "/contact/"

# SEO
seo:
  type: "Organization"
  name: "Sol Ligam"
  description: "Sol Ligam accompagne les structures pour diminuer leur impact carbone, notamment dans l'événementiel. Simulateur gratuit, conseils et outils pour la décarbonation."
  url: "https://solligam.fr"
  logo: "/images/brand/logo.webp"
  links:
    - "https://www.instagram.com/sol_ligam/"
    - "https://www.linkedin.com/company/sol-ligam/"
  telephone: ""
  email: "contact@solligam.fr"
  address:
    street_address: "215 cours du maréchal gallieni"
    locality: "Bordeaux"
    postal_code: "33000"
    country: "FR"

# Open Graph / Social Media
og_image: "/images/brand/logo.webp"
twitter:
  card: "summary_large_image"
  site: "@sol_ligam"
  creator: "@sol_ligam"
facebook:
  app_id: ""
  page: "https://www.facebook.com/solligam" # si tu as une page Facebook

# Additional SEO settings
webmaster_verifications:
  google: "AAAAA"
  bing: "AAAAA"
  yandex: ""

# Structured data
organization:
  name: "SAS Sol Ligam"
  legal_name: "SAS Sol Ligam"
  description: "Accompagnement pour la réduction de l'impact carbone, conseils, outils et simulateur gratuit."
  url: "https://solligam.fr"
  logo: "https://solligam.fr/images/brand/logo.webp"
  address:
    street_address: "215 cours du maréchal gallieni"
    locality: "Bordeaux"
    postal_code: "33000"
    country: "FR"
  contact_point:
    type: "customer service"
    email: "contact@solligam.fr"
    telephone: ""
    contact_type: "customer support"
    area_served: "FR"
    available_language: ["fr"]
  same_as:
    - "https://www.instagram.com/sol_ligam/"
    - "https://www.linkedin.com/company/sol-ligam/"
    - "https://monbilancarbone.solligam.fr"